
# Parameters were selected as follows. First, kb,kp,ks=1 and k1,k2,k3 were
# adjusted until base+penalty effort for QWERTY had a ratio of 60:90:100 for
# components of the sum associated exclusively with k1, k2 and k3.
#
# Keyboard effort
# ------------------------------------------------------------
#
# k1                      2.579  60.001  60.001
# k1,k2                   3.868  29.999  90.000
# k1,k2,k3                4.298  10.000 100.000
# b                       2.726  41.040  41.009
# p                       1.573  23.682 273.292
# ph                      0.000   0.000   0.000
# pr                      0.636  40.008  40.008
# pf                      0.636  40.008  81.007
# s                       2.343  35.278 100.000

#
# Then, kb, kp, ks were set to values that made base, penalty and stroke path
# components all 1.000 for QWERTY, for a total effort of 3.000.
#
# Keyboard effort
# ------------------------------------------------------------
# k1                      1.236  61.8  61.8
# k1,k2                   1.817  29.1  90.9
# k1,k2,k3                2.000   9.1 100.0
# b                       1.000  33.3  33.3
# p                       1.000  33.3 200.0
# ph                      0.000   0.0   0.0
# pr                      0.408  40.8  40.8
# pf                      0.408  40.8  81.7
# s                       1.000  33.3 100.0
# all                     3.000 100.0 100.0
#
# Note that penalty weights for row and finger were previously set to
# make these two components equal contributors to the total penalty.

[effort]
kb = 0.367
kp = 0.6355
ks = 0.427

k1 = 1
k2 = 0.3762 
k3 = 0.2426


