[finger distance]
# The baseline effort is based on the distance required
# to reach each key position. Assumed here is a standard 101-key
# layout and conventional finger placement. These distances are
# combined with other typing effort model parameters, such as
# key-finger assignment, finger penalties, hand penalties,
# and path stroke.
#
# The units of distance are arbitrary, but their relative values
# should correspond to actual key distances.
#
# I've replaced the distances with measurements taken from a standard keyboard layout in Kicad (PCB design software).
# Most keyboards have fixed key spacing, and row-staggered keyboards have a standard layout.

[effort]
#       ~      1      2      3      4      5      6      7      8      9      0      -      =
row 1 = 5.0626 4.0691 4.0691 4.0691 4.0691 3.8397 5.0626 4.0691 4.0691 4.0691 4.0691 3.8396 4.4929
#       q      w      e      r      t      y      u      i      o      p      [      ]      \
row 2 = 1.9636 1.9636 1.9636 1.9636 2.3812 3.0495 1.9636 1.9636 1.9636 1.9636 2.3812 3.8396 5.5743
#       a      s      d      f      g      h      j      k      l      ;      '
row 3 = 0.0000 0.0000 0.0000 0.0000 1.9050 1.9050 0.0000 0.0000 0.0000 0.0000 1.9050
#       z      x      c      v      b      n      m      ,      .      /
row 4 = 1.9050 1.9050 1.9050 1.9050 3.4343 1.9050 1.9050 1.9050 1.9050 1.9050
